### ISSUE TITLE
Create empty "shared" folder for quicker setup

### ISSUE THREAD

**Issue by jmernin** [lucab85/avg#14]
How about creating an empty "share" folder in the AVG repo so that the step to create this (during the setup phase) is not actually needed?

For sure, people can select/use a different folder later on but for most use cases (and in the interest in increased adoption), maybe this would help?

**Comment by lucab85** [comment]
Unfortunately, this is not possible for technical reasons.
The `share` folder is used to share files between the container and the host system.
The `avg` container run completely isolated from the host system for security reasons so it's not possible to alter in any way the host system.
The only way is to manually create a folder and map it to the `/share` path of the container.
This step is described in the `Setup` step of the [README](https://github.com/lucab85/avg/blob/master/README.md) file.
