### ISSUE TITLE
Add language support

### ISSUE THREAD

**Issue by jmernin** [lucab85/avg#15]
In addition to being able to specify different voices, perhaps we could allow different languages to be specified as well. I suggest this because I saw that Amazon Polly supports both voices and languages, which are technically different things.

That way, it could be possible to produce multiple different videos of the same presentation, in different languages but using an accent that is suited to each language.

**Comment by lucab85** [comment]
You could obtain the specific audio for your region by customizing it according to the `AVG_VOICE` variable in your `.env` file.
For example:
- Spanish (US) voice using AWS Polly Service:
```
AVG_SERVICE=amazon
AVG_VOICE=Lupe
```
- English (US)  voice using AWS Polly Service:
```
AVG_SERVICE=amazon
AVG_VOICE=Joey
```
Reference to [Voices in Amazon Polly](https://docs.aws.amazon.com/polly/latest/dg/voicelist.html) and [Supported voices and languages for Google Cloud Text-to-Speech ](https://cloud.google.com/text-to-speech/docs/voices)
