### ISSUE TITLE
Clarify which AWS service is doing the text-to-speech conversion

### ISSUE THREAD

**Issue by jmernin** [lucab85/avg#9]
Provide some additional detailed in the README about how the text-to-speech conversion is being done, so people can better understand the other values they could provide in the default.env file, for example.

In fact, perhaps we could add comments into default.env, pointing people to the relevant AWS page to see the available values for each variable.

**Comment by lucab85** [comment]
- Amazon option uses the [Amazon Polly](https://docs.aws.amazon.com/polly/latest/dg/listening-voices.html)
- Google option uses [Cloud Text-to-Speech](https://cloud.google.com/text-to-speech)

**Comment by jmernin** [comment]
Maybe we also add some notes that also describe how to listen to samples of the voices that each service offers.

**Comment by jmernin** [comment]
PR above approved so closing this issue now too.
